// Canonical country list for the registration form's country picker — replaces the previous
// free-text input (any typo/format was accepted before, e.g. "morocco" vs "Morocco" vs "MA").
// ISO 3166-1 alpha-2 codes are kept alongside the display name so callers that only have the
// User.country name (the format actually stored in the database, see prisma/schema.prisma) can
// still resolve an ISO code — e.g. Crisis City's civic-color pack lookup, which is keyed by ISO
// code (components/crisis-city/data/countryFlags.js, atelier/data/countryGeo.js).
export interface CountryOption {
  name: string
  isoCode: string
}

export const COUNTRIES: CountryOption[] = [
  { name: 'Afghanistan', isoCode: 'AF' },
  { name: 'Albania', isoCode: 'AL' },
  { name: 'Algeria', isoCode: 'DZ' },
  { name: 'Andorra', isoCode: 'AD' },
  { name: 'Angola', isoCode: 'AO' },
  { name: 'Antigua and Barbuda', isoCode: 'AG' },
  { name: 'Argentina', isoCode: 'AR' },
  { name: 'Armenia', isoCode: 'AM' },
  { name: 'Australia', isoCode: 'AU' },
  { name: 'Austria', isoCode: 'AT' },
  { name: 'Azerbaijan', isoCode: 'AZ' },
  { name: 'Bahamas', isoCode: 'BS' },
  { name: 'Bahrain', isoCode: 'BH' },
  { name: 'Bangladesh', isoCode: 'BD' },
  { name: 'Barbados', isoCode: 'BB' },
  { name: 'Belarus', isoCode: 'BY' },
  { name: 'Belgium', isoCode: 'BE' },
  { name: 'Belize', isoCode: 'BZ' },
  { name: 'Benin', isoCode: 'BJ' },
  { name: 'Bhutan', isoCode: 'BT' },
  { name: 'Bolivia', isoCode: 'BO' },
  { name: 'Bosnia and Herzegovina', isoCode: 'BA' },
  { name: 'Botswana', isoCode: 'BW' },
  { name: 'Brazil', isoCode: 'BR' },
  { name: 'Brunei', isoCode: 'BN' },
  { name: 'Bulgaria', isoCode: 'BG' },
  { name: 'Burkina Faso', isoCode: 'BF' },
  { name: 'Burundi', isoCode: 'BI' },
  { name: 'Cabo Verde', isoCode: 'CV' },
  { name: 'Cambodia', isoCode: 'KH' },
  { name: 'Cameroon', isoCode: 'CM' },
  { name: 'Canada', isoCode: 'CA' },
  { name: 'Central African Republic', isoCode: 'CF' },
  { name: 'Chad', isoCode: 'TD' },
  { name: 'Chile', isoCode: 'CL' },
  { name: 'China', isoCode: 'CN' },
  { name: 'Colombia', isoCode: 'CO' },
  { name: 'Comoros', isoCode: 'KM' },
  { name: 'Congo (Republic of the)', isoCode: 'CG' },
  { name: 'Congo (Democratic Republic of the)', isoCode: 'CD' },
  { name: 'Costa Rica', isoCode: 'CR' },
  { name: "Côte d'Ivoire", isoCode: 'CI' },
  { name: 'Croatia', isoCode: 'HR' },
  { name: 'Cuba', isoCode: 'CU' },
  { name: 'Cyprus', isoCode: 'CY' },
  { name: 'Czechia', isoCode: 'CZ' },
  { name: 'Denmark', isoCode: 'DK' },
  { name: 'Djibouti', isoCode: 'DJ' },
  { name: 'Dominica', isoCode: 'DM' },
  { name: 'Dominican Republic', isoCode: 'DO' },
  { name: 'Ecuador', isoCode: 'EC' },
  { name: 'Egypt', isoCode: 'EG' },
  { name: 'El Salvador', isoCode: 'SV' },
  { name: 'Equatorial Guinea', isoCode: 'GQ' },
  { name: 'Eritrea', isoCode: 'ER' },
  { name: 'Estonia', isoCode: 'EE' },
  { name: 'Eswatini', isoCode: 'SZ' },
  { name: 'Ethiopia', isoCode: 'ET' },
  { name: 'Fiji', isoCode: 'FJ' },
  { name: 'Finland', isoCode: 'FI' },
  { name: 'France', isoCode: 'FR' },
  { name: 'Gabon', isoCode: 'GA' },
  { name: 'Gambia', isoCode: 'GM' },
  { name: 'Georgia', isoCode: 'GE' },
  { name: 'Germany', isoCode: 'DE' },
  { name: 'Ghana', isoCode: 'GH' },
  { name: 'Greece', isoCode: 'GR' },
  { name: 'Grenada', isoCode: 'GD' },
  { name: 'Guatemala', isoCode: 'GT' },
  { name: 'Guinea', isoCode: 'GN' },
  { name: 'Guinea-Bissau', isoCode: 'GW' },
  { name: 'Guyana', isoCode: 'GY' },
  { name: 'Haiti', isoCode: 'HT' },
  { name: 'Honduras', isoCode: 'HN' },
  { name: 'Hungary', isoCode: 'HU' },
  { name: 'Iceland', isoCode: 'IS' },
  { name: 'India', isoCode: 'IN' },
  { name: 'Indonesia', isoCode: 'ID' },
  { name: 'Iran', isoCode: 'IR' },
  { name: 'Iraq', isoCode: 'IQ' },
  { name: 'Ireland', isoCode: 'IE' },
  { name: 'Israel', isoCode: 'IL' },
  { name: 'Italy', isoCode: 'IT' },
  { name: 'Jamaica', isoCode: 'JM' },
  { name: 'Japan', isoCode: 'JP' },
  { name: 'Jordan', isoCode: 'JO' },
  { name: 'Kazakhstan', isoCode: 'KZ' },
  { name: 'Kenya', isoCode: 'KE' },
  { name: 'Kiribati', isoCode: 'KI' },
  { name: 'Kuwait', isoCode: 'KW' },
  { name: 'Kyrgyzstan', isoCode: 'KG' },
  { name: 'Laos', isoCode: 'LA' },
  { name: 'Latvia', isoCode: 'LV' },
  { name: 'Lebanon', isoCode: 'LB' },
  { name: 'Lesotho', isoCode: 'LS' },
  { name: 'Liberia', isoCode: 'LR' },
  { name: 'Libya', isoCode: 'LY' },
  { name: 'Liechtenstein', isoCode: 'LI' },
  { name: 'Lithuania', isoCode: 'LT' },
  { name: 'Luxembourg', isoCode: 'LU' },
  { name: 'Madagascar', isoCode: 'MG' },
  { name: 'Malawi', isoCode: 'MW' },
  { name: 'Malaysia', isoCode: 'MY' },
  { name: 'Maldives', isoCode: 'MV' },
  { name: 'Mali', isoCode: 'ML' },
  { name: 'Malta', isoCode: 'MT' },
  { name: 'Marshall Islands', isoCode: 'MH' },
  { name: 'Mauritania', isoCode: 'MR' },
  { name: 'Mauritius', isoCode: 'MU' },
  { name: 'Mexico', isoCode: 'MX' },
  { name: 'Micronesia', isoCode: 'FM' },
  { name: 'Moldova', isoCode: 'MD' },
  { name: 'Monaco', isoCode: 'MC' },
  { name: 'Mongolia', isoCode: 'MN' },
  { name: 'Montenegro', isoCode: 'ME' },
  { name: 'Morocco', isoCode: 'MA' },
  { name: 'Mozambique', isoCode: 'MZ' },
  { name: 'Myanmar', isoCode: 'MM' },
  { name: 'Namibia', isoCode: 'NA' },
  { name: 'Nauru', isoCode: 'NR' },
  { name: 'Nepal', isoCode: 'NP' },
  { name: 'Netherlands', isoCode: 'NL' },
  { name: 'New Zealand', isoCode: 'NZ' },
  { name: 'Nicaragua', isoCode: 'NI' },
  { name: 'Niger', isoCode: 'NE' },
  { name: 'Nigeria', isoCode: 'NG' },
  { name: 'North Korea', isoCode: 'KP' },
  { name: 'North Macedonia', isoCode: 'MK' },
  { name: 'Norway', isoCode: 'NO' },
  { name: 'Oman', isoCode: 'OM' },
  { name: 'Pakistan', isoCode: 'PK' },
  { name: 'Palau', isoCode: 'PW' },
  { name: 'Palestine', isoCode: 'PS' },
  { name: 'Panama', isoCode: 'PA' },
  { name: 'Papua New Guinea', isoCode: 'PG' },
  { name: 'Paraguay', isoCode: 'PY' },
  { name: 'Peru', isoCode: 'PE' },
  { name: 'Philippines', isoCode: 'PH' },
  { name: 'Poland', isoCode: 'PL' },
  { name: 'Portugal', isoCode: 'PT' },
  { name: 'Qatar', isoCode: 'QA' },
  { name: 'Romania', isoCode: 'RO' },
  { name: 'Russia', isoCode: 'RU' },
  { name: 'Rwanda', isoCode: 'RW' },
  { name: 'Saint Kitts and Nevis', isoCode: 'KN' },
  { name: 'Saint Lucia', isoCode: 'LC' },
  { name: 'Saint Vincent and the Grenadines', isoCode: 'VC' },
  { name: 'Samoa', isoCode: 'WS' },
  { name: 'San Marino', isoCode: 'SM' },
  { name: 'Sao Tome and Principe', isoCode: 'ST' },
  { name: 'Saudi Arabia', isoCode: 'SA' },
  { name: 'Senegal', isoCode: 'SN' },
  { name: 'Serbia', isoCode: 'RS' },
  { name: 'Seychelles', isoCode: 'SC' },
  { name: 'Sierra Leone', isoCode: 'SL' },
  { name: 'Singapore', isoCode: 'SG' },
  { name: 'Slovakia', isoCode: 'SK' },
  { name: 'Slovenia', isoCode: 'SI' },
  { name: 'Solomon Islands', isoCode: 'SB' },
  { name: 'Somalia', isoCode: 'SO' },
  { name: 'South Africa', isoCode: 'ZA' },
  { name: 'South Korea', isoCode: 'KR' },
  { name: 'South Sudan', isoCode: 'SS' },
  { name: 'Spain', isoCode: 'ES' },
  { name: 'Sri Lanka', isoCode: 'LK' },
  { name: 'Sudan', isoCode: 'SD' },
  { name: 'Suriname', isoCode: 'SR' },
  { name: 'Sweden', isoCode: 'SE' },
  { name: 'Switzerland', isoCode: 'CH' },
  { name: 'Syria', isoCode: 'SY' },
  { name: 'Taiwan', isoCode: 'TW' },
  { name: 'Tajikistan', isoCode: 'TJ' },
  { name: 'Tanzania', isoCode: 'TZ' },
  { name: 'Thailand', isoCode: 'TH' },
  { name: 'Timor-Leste', isoCode: 'TL' },
  { name: 'Togo', isoCode: 'TG' },
  { name: 'Tonga', isoCode: 'TO' },
  { name: 'Trinidad and Tobago', isoCode: 'TT' },
  { name: 'Tunisia', isoCode: 'TN' },
  { name: 'Türkiye', isoCode: 'TR' },
  { name: 'Turkmenistan', isoCode: 'TM' },
  { name: 'Tuvalu', isoCode: 'TV' },
  { name: 'Uganda', isoCode: 'UG' },
  { name: 'Ukraine', isoCode: 'UA' },
  { name: 'United Arab Emirates', isoCode: 'AE' },
  { name: 'United Kingdom', isoCode: 'GB' },
  { name: 'United States', isoCode: 'US' },
  { name: 'Uruguay', isoCode: 'UY' },
  { name: 'Uzbekistan', isoCode: 'UZ' },
  { name: 'Vanuatu', isoCode: 'VU' },
  { name: 'Vatican City', isoCode: 'VA' },
  { name: 'Venezuela', isoCode: 'VE' },
  { name: 'Vietnam', isoCode: 'VN' },
  { name: 'Yemen', isoCode: 'YE' },
  { name: 'Zambia', isoCode: 'ZM' },
  { name: 'Zimbabwe', isoCode: 'ZW' },
]

const NAME_TO_CODE: Record<string, string> = Object.fromEntries(
  COUNTRIES.map((c) => [c.name.toLowerCase(), c.isoCode])
)

// Backward-compatible lookup for country names stored before this list existed (free text —
// e.g. seed data uses "UAE" instead of "United Arab Emirates").
const LEGACY_ALIASES: Record<string, string> = {
  uae: 'AE',
  turkey: 'TR',
  'ivory coast': 'CI',
  'democratic republic of congo': 'CD',
  'republic of congo': 'CG',
}

export function getIsoCodeByCountryName(name: string | null | undefined): string | undefined {
  if (!name) return undefined
  const key = name.trim().toLowerCase()
  return NAME_TO_CODE[key] || LEGACY_ALIASES[key]
}
